version: "3.9"

services:
  finshield-api:
    build: .
    container_name: finshield-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload